/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./components/AppSidebar.vue')['default']
    AppTopbar: typeof import('./components/AppTopbar.vue')['default']
    EmailNotificationBridge: typeof import('./components/EmailNotificationBridge.vue')['default']
    EmptyStateWithGlow: typeof import('./components/EmptyStateWithGlow.vue')['default']
    ImmersiveHeader: typeof import('./components/ImmersiveHeader.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    MacAppShell: typeof import('./components/MacAppShell.vue')['default']
    MacControlCenter: typeof import('./components/MacControlCenter.vue')['default']
    MacFunctionalPane: typeof import('./components/MacFunctionalPane.vue')['default']
    MacGlobalRail: typeof import('./components/MacGlobalRail.vue')['default']
    MacInspectorPanel: typeof import('./components/MacInspectorPanel.vue')['default']
    ModelSelector: typeof import('./components/ModelSelector.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NForm: typeof import('naive-ui')['NForm']
    NFormItem: typeof import('naive-ui')['NFormItem']
    NInput: typeof import('naive-ui')['NInput']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NModal: typeof import('naive-ui')['NModal']
    NPageHeader: typeof import('naive-ui')['NPageHeader']
    NSelect: typeof import('naive-ui')['NSelect']
    NSpace: typeof import('naive-ui')['NSpace']
    NSwitch: typeof import('naive-ui')['NSwitch']
    NTag: typeof import('naive-ui')['NTag']
    NText: typeof import('naive-ui')['NText']
    PasswordResetModal: typeof import('./components/PasswordResetModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiEmptyState: typeof import('./components/ui/UiEmptyState.vue')['default']
    UiPage: typeof import('./components/ui/UiPage.vue')['default']
    UiPageHeader: typeof import('./components/ui/UiPageHeader.vue')['default']
    UiPanel: typeof import('./components/ui/UiPanel.vue')['default']
    UiStat: typeof import('./components/ui/UiStat.vue')['default']
    UiStatusBadge: typeof import('./components/ui/UiStatusBadge.vue')['default']
    UiToolbar: typeof import('./components/ui/UiToolbar.vue')['default']
  }
}
