/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    EmailNotificationBridge: typeof import('./components/EmailNotificationBridge.vue')['default']
    EmptyStateWithGlow: typeof import('./components/EmptyStateWithGlow.vue')['default']
    ImmersiveHeader: typeof import('./components/ImmersiveHeader.vue')['default']
    LoadingSpinner: typeof import('./components/LoadingSpinner.vue')['default']
    MacAppShell: typeof import('./components/MacAppShell.vue')['default']
    MacControlCenter: typeof import('./components/MacControlCenter.vue')['default']
    MacFunctionalPane: typeof import('./components/MacFunctionalPane.vue')['default']
    MacGlobalRail: typeof import('./components/MacGlobalRail.vue')['default']
    MacInspectorPanel: typeof import('./components/MacInspectorPanel.vue')['default']
    ModelSelector: typeof import('./components/ModelSelector.vue')['default']
    NTag: typeof import('naive-ui')['NTag']
    PasswordResetModal: typeof import('./components/PasswordResetModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiEmptyState: typeof import('./components/ui/UiEmptyState.vue')['default']
    UiPage: typeof import('./components/ui/UiPage.vue')['default']
    UiPageHeader: typeof import('./components/ui/UiPageHeader.vue')['default']
    UiPanel: typeof import('./components/ui/UiPanel.vue')['default']
    UiStat: typeof import('./components/ui/UiStat.vue')['default']
    UiStatusBadge: typeof import('./components/ui/UiStatusBadge.vue')['default']
    UiToolbar: typeof import('./components/ui/UiToolbar.vue')['default']
  }
}
